# Generated by Django 3.2.13 on 2022-06-15 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_dir',
            field=models.FileField(blank=True, null=True, upload_to='csv', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
