# Generated by Django 3.2.13 on 2022-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_post_file_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_dir',
            field=models.FileField(blank=True, null=True, upload_to='csv'),
        ),
    ]
