# Generated by Django 3.2.10 on 2022-06-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_post_file_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_dir',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
    ]
