# Generated by Django 3.2.10 on 2022-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_post_file_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_dir',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='ファイル'),
        ),
    ]
